name: 'setup-java'
description: 'Setup Java'

inputs:
  java-version:
    description: 'The Java version to set up'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#java
    - if: inputs.java-version == 8 || inputs.java-version == 11 || inputs.java-version == 17 || inputs.java-version == 21
      name: Setup Java ${{ inputs.java-version }} using bash
      shell: bash
      # language=bash
      run: |
        echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java-version }}_X64)" >> "$GITHUB_ENV"
    - if: inputs.java-version != 8 && inputs.java-version != 11 && inputs.java-version != 17 && inputs.java-version != 21
      name: Setup Java ${{ inputs.java-version }} using setup-java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    - name: Setup problem matcher
      shell: bash
      env:
        MATCHER: |
          {
            "problemMatcher": [
              {
                  "owner": "javac",
                  "pattern": [
                    {
                      "regexp": "^([^:]+\\.java):(\\d+): (warning|error): (.+?)$",
                      "file": 1,
                      "line": 2,
                      "severity": 3,
                      "message": 4
                    }
                  ]
              }
            ]
          }
      run: |
        mkdir /tmp/problem-matchers/
        echo "$MATCHER" > /tmp/problem-matchers/javac.json
        echo "::add-matcher::/tmp/problem-matchers/javac.json"