name: Add repository webhook
 
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The name of the repo to add a webhook to'
        required: true
      hook:
        description: 'The URL of the webhook'
        required: true

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.0.18'
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 376723
          private_key: ${{ secrets.APPLICATION_KEY }}
          repository: neoforged/${{ github.event.inputs.repo }}
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Add webhook
        run: groovy .github/workflows/scripts/add_webhook.groovy
        env:
          AUTH_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
          REPO_NAME: neoforged/${{ github.event.inputs.repo }}
          EVENT_PATH: ${{ github.event_path }}