name: 'Publish PR JCC output'

on:
  workflow_call:
    inputs:
      beta_version_pattern:
        type: string
        required: false
        default: '.+-beta'
        description: 'The pattern that indicates when a version is beta and can accept further breaking changes'
    
    secrets:
        JCC_GH_APP_ID:
            required: true
        JCC_GH_APP_KEY:
            required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: ${{ secrets.JCC_GH_APP_ID }}
          private_key: ${{ secrets.JCC_GH_APP_KEY }}
          repository: ${{ github.repository }}
      - name: Publish JCC output
        uses: neoforged/action-jar-compatibility@v1
        env:
          GITHUB_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
        with:
          self-name: 'neoforged-compatibility-checks[bot]'
          beta-version-pattern: ${{ inputs.beta_version_pattern }}