name: Run Renovate

on:
  workflow_dispatch:
    inputs:
      repositories:
        type: string
        description: 'The repositories to run renovate against'
        required: true
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string

concurrency:
    group: renovate-${{ github.event.inputs.repositories }}

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Generate a token for the org
              id: gen_repo_token
              uses: kattecon/gh-app-access-token-gen@v1
              with:
                app_id: 931948
                private_key: ${{ secrets.RENOVATE_APPLICATION_KEY }}
                installation_id: 52268154
            - name: Checkout upstream
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                persist-credentials: false
            - name: Cache Renovate cache dir
              uses: actions/cache@v4
              with:
                path: /tmp/renovatecaches
                key: renovate-${{ github.run_id }}
                restore-keys: renovate-
            - run: |
                mkdir -p /tmp/renovatecaches
                sudo chown -R 1000 /tmp/renovatecaches
            - name: Self-hosted Renovate
              uses: renovatebot/github-action@v40.1.12
              env:
                  # Repository taken from variable to keep configuration file generic
                  RENOVATE_REPOSITORIES: ${{ github.event.inputs.repositories }}
                  # Onboarding not needed for self hosted (for now)
                  RENOVATE_ONBOARDING: "true"
                  # Username for GitHub authentication (should match GitHub App name + [bot])
                  RENOVATE_USERNAME: "neoforged-renovate[bot]"
                  # Git commit author used, must match GitHub App
                  RENOVATE_GIT_AUTHOR: "neoforged-renovate[bot] <174042230+neoforged-renovate[bot]@users.noreply.github.com>"
                  # Use GitHub API to create commits (this allows for signed commits from GitHub App)
                  RENOVATE_PLATFORM_COMMIT: "true"
                  # Override schedule if set
                  RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
                  LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
              with:
                  configurationFile: renovate_admin_config.json
                  token: '${{ steps.gen_repo_token.outputs.token }}'
                  renovate-version: 38.38.1
            - run: sudo chown -R $(whoami) /tmp/renovatecaches