name: Start a new branch on kits
 
on:
  workflow_dispatch:
    inputs:
        upstream_branch:
          type: string
          description: 'The upstream branch to base the changes off of'
        mc_version:
          type: string
          description: 'The MC version to start the kits branch for'
          required: true
        neoform_version:
          type: string
          description: 'The neoform version'
          required: true
        
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.x'
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 436140
          private_key: ${{ secrets.SNOWLANCE_PRIVATE_KEY }}
          repository: neoforged/kits
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: neoforged/kits
          token: ${{ steps.gen_repo_token.outputs.token }}
      
      - name: Configure git
        run: |
          git config --global user.name "snow-lance[bot]"
          git config --global user.email "150522644+snow-lance[bot]@users.noreply.github.com"

      - name: Add and fetch upstream
        run: |
          git remote add upstream https://github.com/neoforged/neoforge
          git fetch upstream ${{ inputs.upstream_branch }}
          git switch -c ${{ inputs.mc_version }} upstream/${{ inputs.upstream_branch }}

      - name: Update versions
        run: |
          sed -i -E "s/minecraft_version=[0-9a-z-_\.]+/minecraft_version=$MC_VERSION/g" gradle.properties
          sed -i -E "s/neoform_version=[0-9a-z-_\.]+/neoform_version=$NEOFORM_VERSION/g" gradle.properties
        env:
          MC_VERSION: ${{ inputs.mc_version }}
          NEOFORM_VERSION: ${{ inputs.neoform_version }}

      - name: Commit version update
        run: |
          git add gradle.properties
          git commit -m "Update versions"
          git push origin +${{ inputs.mc_version }}:${{ inputs.mc_version }}

      - name: Make Gradlew executable
        # language=bash
        run: chmod +x ./gradlew # Thanks Windows

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: setup -Pupdating
      
      - name: Commit MC Sources
        run: |
          git commit -m "MC Sources"
          git add --force projects/base/src
      - name: Commit Rejects
        run: |
          git add --force /patches-/
          git add --force *.patch.rej
          git add --force /projects/*/rejects/
          git commit -m "Rejects"
      - name: Push
        run: |
          git push